package game.res;

import java.awt.Font;

import javax.swing.ImageIcon;

public interface Utilities {

	int BOARD_HEIGHT = 600;
	int BOARD_WIDTH = 1000;
	int FLOOR = BOARD_HEIGHT - 160;
	int INIT_POS = 80;
	int DEALY = 100;
	int BACKGROUNG_SPEED = -7;
	int FRUIT_LEVEL_1 = BOARD_HEIGHT - 320;
	int FRUIT_LEVEL_2 = BOARD_HEIGHT - 400;

	int JACKPOT_NUMBER = 3;
	int BANANA_NUMBER = 2;
	int APPLE_NUMBER = 1;

	int BIRD_NUM = 2;
	int LIZARD_NUM = 3;
	int SNAIL_NUM = 1;
	int ROCK_NUM = 4;

	Background BACKGROUND1 = new Background(0, 15000, new ImageIcon(Utilities.class.getResource("back.jpg")));
	int ENEMY_XLOC[] = { BOARD_WIDTH + 1300, BOARD_WIDTH + 2380, BOARD_WIDTH + 2530, BOARD_WIDTH + 3570,
			BOARD_WIDTH + 3975, BOARD_WIDTH + 4240, BOARD_WIDTH + 4400, BOARD_WIDTH + 5000, BOARD_WIDTH + 5800,
			BOARD_WIDTH + 6230, BOARD_WIDTH + 6750, BOARD_WIDTH + 7860, BOARD_WIDTH + 8540, BOARD_WIDTH + 9020,
			BOARD_WIDTH + 10300, BOARD_WIDTH + 10500, BOARD_WIDTH + 11000 };

	int FRUITS_XLOC[] = { BOARD_WIDTH + 130, BOARD_WIDTH + 535, BOARD_WIDTH + 2130, BOARD_WIDTH + 2730,
			BOARD_WIDTH + 3330, BOARD_WIDTH + 3700, BOARD_WIDTH + 4230, BOARD_WIDTH + 4500, BOARD_WIDTH + 4800,
			BOARD_WIDTH + 5000, BOARD_WIDTH + 5500, BOARD_WIDTH + 5600, BOARD_WIDTH + 6000, BOARD_WIDTH + 6500,
			BOARD_WIDTH + 7000, BOARD_WIDTH + 7300, BOARD_WIDTH + 8000, BOARD_WIDTH + 8700, BOARD_WIDTH + 9100,
			BOARD_WIDTH + 9500, BOARD_WIDTH + 10100, BOARD_WIDTH + 10200, BOARD_WIDTH + 10300, BOARD_WIDTH + 11200,
			BOARD_WIDTH + 12000 };

	int FRUITS_YlOC[] = { FRUIT_LEVEL_1, FRUIT_LEVEL_2, FRUIT_LEVEL_2, FRUIT_LEVEL_2, FRUIT_LEVEL_1, FRUIT_LEVEL_2,
			FRUIT_LEVEL_2, FRUIT_LEVEL_2, FRUIT_LEVEL_2, FRUIT_LEVEL_1, FRUIT_LEVEL_2, FRUIT_LEVEL_2, FRUIT_LEVEL_1,
			FRUIT_LEVEL_1, FRUIT_LEVEL_2, FRUIT_LEVEL_1, FRUIT_LEVEL_2, FRUIT_LEVEL_1, FRUIT_LEVEL_1, FRUIT_LEVEL_2,
			FRUIT_LEVEL_1, FRUIT_LEVEL_1, FRUIT_LEVEL_1, FRUIT_LEVEL_2, FRUIT_LEVEL_2 };

	int STONE_XLOC[] = { BOARD_WIDTH + 2830, BOARD_WIDTH + 3330, BOARD_WIDTH + 7200, BOARD_WIDTH + 8700 };
	int FIRE_XLOC[] = { BOARD_WIDTH + 1830, BOARD_WIDTH + 2330, BOARD_WIDTH + 4000, BOARD_WIDTH + 10900 };

	int FRUIT_SELECTOR[] = { JACKPOT_NUMBER, BANANA_NUMBER, APPLE_NUMBER, BANANA_NUMBER, APPLE_NUMBER, APPLE_NUMBER,
			APPLE_NUMBER, BANANA_NUMBER, APPLE_NUMBER, BANANA_NUMBER, BANANA_NUMBER, APPLE_NUMBER, APPLE_NUMBER,
			APPLE_NUMBER, APPLE_NUMBER, APPLE_NUMBER, APPLE_NUMBER, APPLE_NUMBER, BANANA_NUMBER, APPLE_NUMBER,
			APPLE_NUMBER, APPLE_NUMBER, APPLE_NUMBER, APPLE_NUMBER, JACKPOT_NUMBER };

	int ENEMY_SELECTOR[] = { BIRD_NUM, BIRD_NUM, LIZARD_NUM, BIRD_NUM, ROCK_NUM, SNAIL_NUM, SNAIL_NUM, SNAIL_NUM,
			SNAIL_NUM, BIRD_NUM, BIRD_NUM, LIZARD_NUM, SNAIL_NUM, ROCK_NUM, BIRD_NUM, ROCK_NUM, BIRD_NUM };

	Font ENERGY_FONT = new Font("Arial", Font.BOLD, 15);
	Font MESSAGE_FONT = new Font("Arial", Font.BOLD, 50);
	Font FINAL_SCORE_FONT = new Font("Arial", Font.BOLD, 40);
}
